services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    depends_on:
      - db
  
  db:
    build: .
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: generaltoolsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  postgres_data: