# Generated by Django 5.1.6 on 2025-07-19 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permissionrights",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("publishEvent", "Allowed to publish events"),
                    ("requestDelegatedEvent", "Allowed to request delegated events"),
                    ("approveDelegatedEvent", "Allowed to approve delegated events"),
                    ("viewDelegatedEventList", "Allowed to view delegated events"),
                    ("viewPublishedEventList", "Allowed to view published events"),
                ),
            },
        ),
    ]
