# Generated by Django 5.1.6 on 2025-07-19 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0002_alter_permissionrights_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventowners",
            name="isActive",
        ),
        migrations.AddField(
            model_name="eventowners",
            name="expiration",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 19, 14, 9, 45, 152767)
            ),
            preserve_default=False,
        ),
    ]
