# Generated by Django 5.1.6 on 2025-07-19 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0003_remove_eventowners_isactive_eventowners_expiration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postedevents",
            old_name="reasonApproved",
            new_name="reason",
        ),
    ]
