# Generated by Django 5.1.6 on 2025-07-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0004_rename_reasonapproved_postedevents_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="delegatedevents",
            name="zoomRequired",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="postedevents",
            name="zoomRequired",
            field=models.BooleanField(default=True),
        ),
    ]
