# Generated by Django 5.1.7 on 2026-03-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0005_delegatedevents_zoomrequired_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventowners",
            name="isPermanent",
            field=models.BooleanField(default=False),
        ),
    ]
