# Generated by Django 5.1.7 on 2026-05-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0006_eventowners_ispermanent"),
    ]

    operations = [
        migrations.AddField(
            model_name="delegatedevents",
            name="eventType",
            field=models.IntegerField(default=2),
        ),
    ]
