# Generated by Django 5.1.7 on 2026-06-01 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_eventowners_ispermanent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionrights',
            options={'default_permissions': (), 'managed': False, 'permissions': (('publishEvent', 'Allowed to publish events'), ('requestDelegatedEvent', 'Allowed to request delegated events'), ('approveDelegatedEvent', 'Allowed to approve delegated events'), ('viewDelegatedEventList', 'Allowed to view delegated events'), ('viewPublishedEventList', 'Allowed to view published events'), ('manageLinkTree', 'Allowed to manage link trees, items, and QR codes'), ('viewLinkMetrics', 'Allowed to view link tree click/scan metrics'))},
        ),
        migrations.CreateModel(
            name='LinkTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Used in the public URL, e.g. 'links' → /t/links/. Lowercase, no spaces.", max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional blurb shown under the title on the public page.')),
                ('visibility', models.IntegerField(choices=[(0, 'Public — anyone with the link'), (1, 'Members only — requires login')], default=0)),
                ('isActive', models.BooleanField(default=True, help_text='Uncheck to take the whole tree offline (returns 404).')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkTrees', to='tools.eventowners')),
            ],
            options={
                'verbose_name': 'Link Tree',
            },
        ),
        migrations.CreateModel(
            name='LinkTreeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('kind', models.IntegerField(choices=[(0, 'Manual link'), (1, 'Wiki link (auto-surfaced from Outline)'), (2, 'Section header (not a link)')], default=0, help_text='Manual link (you type the URL), wiki link (auto-pulled from Outline), or a section header (a non-clickable heading that groups the items below it).')),
                ('label', models.CharField(blank=True, help_text="Button text — or the heading text for a section header. For wiki links, leave blank to use the document's own title.", max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional smaller line shown under the label.', max_length=300)),
                ('icon', models.CharField(blank=True, help_text='Optional emoji shown before the label, e.g. 📅 or 🗳️.', max_length=8)),
                ('isActive', models.BooleanField(default=True, help_text='Uncheck to hide this item from the page without deleting it.')),
                ('visibleFrom', models.DateTimeField(blank=True, help_text="Optional: don't show the item before this time (UTC).", null=True)),
                ('visibleUntil', models.DateTimeField(blank=True, help_text='Optional: stop showing the item after this time (UTC).', null=True)),
                ('url', models.URLField(blank=True, help_text='Destination URL. Used for manual links (ignored for wiki links and headers).', max_length=2000)),
                ('wikiMode', models.IntegerField(choices=[(0, 'Latest matching document'), (1, 'Pinned document')], default=0, help_text='For wiki links: surface the newest document matching the query, or always link one specific pinned document.')),
                ('wikiQuery', models.CharField(blank=True, help_text="For 'latest matching': title text to search, e.g. 'GBM Agenda'.", max_length=200)),
                ('wikiCollectionId', models.CharField(blank=True, help_text='Optional Outline collection id to scope the search.', max_length=100)),
                ('pinnedWikiDocId', models.CharField(blank=True, help_text="For 'pinned': the Outline document id.", max_length=100)),
                ('resolvedUrl', models.TextField(blank=True, help_text='Auto-filled for wiki links by the sync command — the resolved document URL.')),
                ('resolvedLabel', models.CharField(blank=True, help_text='Auto-filled for wiki links by the sync command — the resolved document title.', max_length=300)),
                ('resolvedAt', models.DateTimeField(blank=True, help_text='When the wiki link was last resolved by the sync command.', null=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tools.linktree')),
            ],
            options={
                'verbose_name': 'Link Tree Item',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Short token in the QR URL, e.g. 'spring-tabling' → /qr/spring-tabling/.", max_length=40, unique=True)),
                ('label', models.CharField(help_text="Human label, e.g. 'Spring 2026 tabling flyer'.", max_length=200)),
                ('campaign', models.CharField(blank=True, help_text="Optional medium/source tag to break down scans, e.g. 'flyer' or 'table-tent'.", max_length=100)),
                ('rawUrl', models.URLField(blank=True, help_text='Target an arbitrary URL instead of a tree/item.', max_length=2000)),
                ('isActive', models.BooleanField(default=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qrCodesCreated', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qrCodes', to='tools.linktreeitem')),
                ('tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qrCodes', to='tools.linktree')),
            ],
            options={
                'verbose_name': 'QR Code',
            },
        ),
        migrations.CreateModel(
            name='LinkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(choices=[(0, 'Web click'), (1, 'QR scan')])),
                ('occurredAt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('destinationUrl', models.TextField(blank=True)),
                ('visitorHash', models.CharField(blank=True, max_length=16)),
                ('uaFamily', models.CharField(blank=True, max_length=40)),
                ('referrerHost', models.CharField(blank=True, max_length=255)),
                ('tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tools.linktree')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tools.linktreeitem')),
                ('qr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tools.qrcode')),
            ],
            options={
                'verbose_name': 'Link Event',
                'indexes': [models.Index(fields=['tree', 'occurredAt'], name='tools_linke_tree_id_373884_idx'), models.Index(fields=['item', 'occurredAt'], name='tools_linke_item_id_246959_idx'), models.Index(fields=['qr', 'occurredAt'], name='tools_linke_qr_id_965836_idx')],
            },
        ),
    ]
