# Generated by Django 5.1.7 on 2026-06-10 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tools', '0008_link_tree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionrights',
            options={'default_permissions': (), 'managed': False, 'permissions': (('publishEvent', 'Allowed to publish events'), ('requestDelegatedEvent', 'Allowed to request delegated events'), ('approveDelegatedEvent', 'Allowed to approve delegated events'), ('viewDelegatedEventList', 'Allowed to view delegated events'), ('viewPublishedEventList', 'Allowed to view published events'), ('manageEventOwners', 'Allowed to manage event owners'), ('manageLinkTree', 'Allowed to manage link trees, items, and QR codes'), ('viewLinkMetrics', 'Allowed to view link tree click/scan metrics'), ('approveAccessRequest', 'Allowed to approve or deny any access request'))},
        ),
        migrations.AlterField(
            model_name='linktree',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Public - anyone with the link'), (1, 'Members only - requires login')], default=0),
        ),
        migrations.AlterField(
            model_name='linktreeitem',
            name='label',
            field=models.CharField(blank=True, help_text="Button text - or the heading text for a section header. For wiki links, leave blank to use the document's own title.", max_length=200),
        ),
        migrations.AlterField(
            model_name='linktreeitem',
            name='resolvedLabel',
            field=models.CharField(blank=True, help_text='Auto-filled for wiki links by the sync command - the resolved document title.', max_length=300),
        ),
        migrations.AlterField(
            model_name='linktreeitem',
            name='resolvedUrl',
            field=models.TextField(blank=True, help_text='Auto-filled for wiki links by the sync command - the resolved document URL.'),
        ),
        migrations.CreateModel(
            name='AccessRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField(help_text="Why the requester needs this access, e.g. 'I run events for the Anti-ICE campaign.'")),
                ('status', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateReviewed', models.DateTimeField(blank=True, default=None, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessRequests', to='auth.group')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessRequests', to='tools.eventowners')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessRequests', to='auth.permission')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessRequestsCreated', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessRequestsReviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Request',
            },
        ),
    ]
