# Generated by Django 5.1.7 on 2026-06-06 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tools', '0008_link_tree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionrights',
            options={'default_permissions': (), 'managed': False, 'permissions': (('publishEvent', 'Allowed to publish events'), ('requestDelegatedEvent', 'Allowed to request delegated events'), ('approveDelegatedEvent', 'Allowed to approve delegated events'), ('viewDelegatedEventList', 'Allowed to view delegated events'), ('viewPublishedEventList', 'Allowed to view published events'), ('manageLinkTree', 'Allowed to manage link trees, items, and QR codes'), ('viewLinkMetrics', 'Allowed to view link tree click/scan metrics'), ('approveAccessRequest', 'Allowed to approve or deny any access request'))},
        ),
        migrations.CreateModel(
            name='AccessRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField(help_text="Why the requester needs this access, e.g. 'I run events for the Anti-ICE campaign.'")),
                ('status', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateReviewed', models.DateTimeField(blank=True, default=None, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessRequests', to='auth.group')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessRequests', to='auth.permission')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessRequestsCreated', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessRequestsReviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Request',
            },
        ),
    ]
