# Generated by Django 5.1.7 on 2026-05-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_link_tree'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifiedHeldNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docId', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('firstNotifiedAt', models.DateTimeField(auto_now_add=True)),
                ('lastNotifiedAt', models.DateTimeField(auto_now=True)),
                ('notifyCount', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Notified Held Note',
            },
        ),
    ]
