# Generated by Django 5.1.7 on 2026-06-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_alter_permissionrights_options_accessrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktree',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Public - anyone with the link'), (1, 'Members only - requires login')], default=0),
        ),
        migrations.AlterField(
            model_name='linktreeitem',
            name='label',
            field=models.CharField(blank=True, help_text="Button text - or the heading text for a section header. For wiki links, leave blank to use the document's own title.", max_length=200),
        ),
        migrations.AlterField(
            model_name='linktreeitem',
            name='resolvedLabel',
            field=models.CharField(blank=True, help_text='Auto-filled for wiki links by the sync command - the resolved document title.', max_length=300),
        ),
        migrations.AlterField(
            model_name='linktreeitem',
            name='resolvedUrl',
            field=models.TextField(blank=True, help_text='Auto-filled for wiki links by the sync command - the resolved document URL.'),
        ),
    ]
