# Generated by Django 5.1.7 on 2026-07-14 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_publishjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listDate', models.DateField(help_text='The date of the national list this snapshot summarizes (not the date it was ingested).', unique=True)),
                ('goodStanding', models.IntegerField()),
                ('member', models.IntegerField()),
                ('lapsed', models.IntegerField()),
                ('total', models.IntegerField()),
                ('sourceEmailDate', models.DateTimeField(blank=True, null=True)),
                ('ingestedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Membership Snapshot',
                'ordering': ['listDate'],
            },
        ),
    ]
