# Generated by Django 5.1.7 on 2026-06-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_alter_linktree_visibility_alter_linktreeitem_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionrights',
            options={'default_permissions': (), 'managed': False, 'permissions': (('publishEvent', 'Allowed to publish events'), ('requestDelegatedEvent', 'Allowed to request delegated events'), ('approveDelegatedEvent', 'Allowed to approve delegated events'), ('viewDelegatedEventList', 'Allowed to view delegated events'), ('viewPublishedEventList', 'Allowed to view published events'), ('manageEventOwners', 'Allowed to manage event owners'), ('manageLinkTree', 'Allowed to manage link trees, items, and QR codes'), ('viewLinkMetrics', 'Allowed to view link tree click/scan metrics'), ('approveAccessRequest', 'Allowed to approve or deny any access request'))},
        ),
    ]
