# Generated by Django 5.1.7 on 2026-06-09 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_alter_permissionrights_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequests',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessRequests', to='tools.eventowners'),
        ),
    ]
